### ISSUE TITLE
accounts <10 days old using ,history command breaks

### ISSUE THREAD

**Issue by ieatcrayons3** [Bobbyperson/nocaro#27]
using ,history on a <10 day old account gives warning that account is <10 days, then additional error message is sent
```python
async with ctx.typing():
            y_axis = await econ.get_history(user)
            if not y_axis:
                await ctx.reply(
                    "Your bouge buck account is not 10 days old. Please try again when it is!"
                )
``` 
should probably look like 
```python
async with ctx.typing():
            y_axis = await econ.get_history(user)
            if not y_axis:
                await ctx.reply(
                    "Your bouge buck account is not 10 days old. Please try again when it is!"
                )
                return
```

**Comment by Bobbyperson** [comment]
so this command is one of the more poorly written parts of code, and really needs a rewrite probably using #13 
even for an account over 10 days old it returns with the error `discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: unhashable type: 'numpy.ndarray'` likely due to one of the dependencies updating since that was never properly tracked until somewhat recently

for now i'll make a commit to disable the history command but leave this issue open to track the progress for the rewrite
